# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a6184b488e036e324ebb8871a49102f3b4503f3cca9ee0d3c06e9abb01515bbcd73407e826298e59204a8816803c0708638bc0a0a7a51ad42e3c7e972286402

test:
  secret_key_base: 582fb1e87455a68435004c43dcf636533e29f889145763795e21ff961de71b5a81915cfb41a241dc555768a7292a61b6f97f10e297b3d86ebdc6c1cd65dc6120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
